# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.11
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: Just_S
book_id: hexxyattributes:hexxyattributesbook
default_branch: 1.20.1-multiloader
github_repo: hexxyattributes
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: HexxyAttributesModModPlugin
hexdoc_plugin_classname: HexxyAttributesModPlugin
java_lang:
    ext: java
    src: java
java_package: net/just_s
mod_display_name: Hexxy Attributes
modid: hexxyattributes
multiloader: true
package_export_root: doc/src/hexdoc_hexxyattributes/_export
package_name: hexdoc-hexxyattributes
package_slug: hexdoc_hexxyattributes
package_src: doc/src/hexdoc_hexxyattributes
pages_url: https://just_s.github.io/hexxyattributes
pattern_regex:
    per_world_value: 'true'
    regex: make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*(?:new )?(?:ActionRegistryEntry|OperationAction)\(\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)
pattern_registry: registry/HexxyAttributesModPatternRegistry.java
